#!/usr/bin/env bash

# Exit immediately if a command fails
set -e

CONF_FILE="devices.conf"
RULE_FILE="/etc/udev/rules.d/99-robot-usb.rules"

echo "=========================================================="
echo "    Praxis Robotics Fleet Provisioning: Config File Reader"
echo "=========================================================="

# 1. Verify the config file exists
if [ ! -f "$CONF_FILE" ]; then
    echo "ERROR: Configuration file '$CONF_FILE' not found!"
    exit 1
fi

# 2. Write the rules to a temporary file first
TMP_RULES=$(mktemp)
echo "# Auto-generated udev rules from $CONF_FILE" > "$TMP_RULES"
echo "# Do not edit this file directly. Edit $CONF_FILE instead." >> "$TMP_RULES"
echo "" >> "$TMP_RULES"

echo "Reading configurations from $CONF_FILE..."

# Parse the config file line by line
while IFS=, read -r name vid pid || [ -n "$name" ]; do
    # Strip leading/trailing whitespace
    name=$(echo "$name" | xargs)
    vid=$(echo "$vid" | xargs)
    pid=$(echo "$pid" | xargs)

    # Skip comments and empty lines
    if [[ -z "$name" || "$name" == \#* ]]; then
        continue
    fi

    echo "  → Configured mapping: /dev/$name (VID: $vid, PID: $pid)"
    
    # Write the formatted udev rule to our temp file
    echo "# $name mapping rule" >> "$TMP_RULES"
    echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$vid\", ATTRS{idProduct}==\"$pid\", SYMLINK+=\"$name\", MODE=\"0666\"" >> "$TMP_RULES"
    echo "" >> "$TMP_RULES"

done < "$CONF_FILE"

# 3. Copy the finished rules file to the secure system directory
sudo cp "$TMP_RULES" "$RULE_FILE"
rm "$TMP_RULES"

# 4. Ensure user is in dialout group
echo "Adding user '$USER' to the 'dialout' group..."
sudo usermod -aG dialout "$USER"

# 5. Reload and trigger the system rules
echo "Applying new udev rules..."
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "----------------------------------------------------------"
echo "SUCCESS: Rules applied!"
echo "----------------------------------------------------------"
echo "Verifying device bindings based on $CONF_FILE:"

# 6. Read the config again to dynamically verify if the links successfully bound
while IFS=, read -r name vid pid || [ -n "$name" ]; do
    name=$(echo "$name" | xargs)
    if [[ -z "$name" || "$name" == \#* ]]; then
        continue
    fi

    if [ -L "/dev/$name" ]; then
        echo "    Device successfully mapped to -> /dev/$name"
    else
        echo "    /dev/$name is NOT active. Is this device plugged in?"
    fi
done < "$CONF_FILE"

echo "=========================================================="
echo "NOTE: Close this SSH session and log back in to apply"
echo "the dialout group permission updates."
echo "=========================================================="
